### PR TITLE
Add CLI, fix page names and static links

### PR DESCRIPTION
**Pull request by hyst3r1a**

### CODE REVIEW

**Comment by dt-iss** [comment]
If you use external dependencies like pyfiglet, they should be noted in requirements file.

**Comment by dt-iss** [comment]
In which location your documentation generator generates the result?

**Comment by dt-iss** [comment]
I can't find the generated documentation, where is it?

**Comment by hyst3r1a** [comment]
Good evening!
Documentation is generated in <executable path>/1 and is currently not
configurable via CLI, can add it to CLI arguments if required
About pyfiglet and other externals - will add them to requirements, thanks
for reminder
All output is commented out for ease of use, so pyfiglet and animated
"processing" are used to give user the feel of working app, because docs
like Azure Powershell take quite big time to process(110k names in all
folders)

вс, 1 дек. 2019 г., 20:06 Dmytro Terletskyi <notifications@github.com>:

**Comment by hyst3r1a** [comment]
CLI now supports output destination parameter
Readme updated with new CLI parameter
Using directives are now being found in code and generated into pages
.md Documentation files are now also being added to dirtree for viewing

**Comment by dt-iss** [comment]
Project: https://github.com/Unity-Technologies/UnityCsReference
Project: https://github.com/statianzo/Fleck

Folder with html pages of documentation is empty. Index, main page and alphabetical index generated.

**Comment by hyst3r1a** [comment]
Checked, works as intended
Fleck creates all files and connects HTML's in a matter of seconds
UnityCsReference creates all files but takes a lot of time creating alphabet index(53000 names in total, while my string operations are not quite optimized)

My successful test:  

cli.py -a /Users/mihailgorsenin/Desktop/Fleck-master "Fleck" /Users/mihailgorsenin/sharplitedocs/Fleck/output/ 

Not sure about write permissions on your machine, maybe your machine's umask prohibits writing
Also, while running the project, .html files(they are used as generation templates) in root directory and all .py files are required

**Review by dt-iss — APPROVED** [review]

**Pull request merged**
